name: meet-app-next
on: 
  push: 
    branches:
      - "main"


jobs:
  vercel:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set ENV 
        uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{secrets.VERCEL_TOKEN}}
          projectName: meet-app-next
          envVariableKeys: GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET,NEXTAUTH_URL,NEXTAUTH_SECRET
        env:
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          TARGET_GOOGLE_CLIENT_ID: production
          TYPE_GOOGLE_CLIENT_ID: plain
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          TARGET_GOOGLE_CLIENT_SECRET: production
          TYPE_GOOGLE_CLIENT_SECRET: plain
          NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
          TARGET_NEXTAUTH_URL: production
          TYPE_NEXTAUTH_URL: plain
          NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
          TARGET_NEXTAUTH_SECRET: production
          TYPE_NEXTAUTH_SECRET: plain

      - name: Deploying..
        uses: amondnet/vercel-action@v20
        with: 
          vercel-token: ${{secrets.VERCEL_TOKEN}}
          vercel-org-id: ${{secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{secrets.PROJECT_ID}}
          vercel-args: "--prod"
          envVariableKeys: ""
